on:
  push:
    branches:
      - chaintools

name: ChainTools Build and Publish
jobs:
  Build:
    name: Build Explorer
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run:  export NODE_OPTIONS="--max_old_space_size=4096"

      - name: Checkout ChainTools Branch
        uses: actions/checkout@v4
        with:
          ref: chaintools

      - name: Yarn Install
        run: yarn install --ignore-engines

      - name: Yarn Build
        run: yarn build-only

      - name: List output files
        run: ls

      - name: Deploy Explorer via SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './dist/'
          remotePath: './explorer.chaintools.tech/dist/'